sudo: required
services:
  - docker

before_install:
  - docker build -t atharavjadhav/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true atharavjadhav/docker-react npm run test

language: generic

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "Docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-579558106006"
  bucket_path: "Docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY